[2022-06-24 06:31:57,715] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-24T06:31:57.067686+00:00 [queued]>
[2022-06-24 06:31:57,727] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-24T06:31:57.067686+00:00 [queued]>
[2022-06-24 06:31:57,727] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-24 06:31:57,728] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-24 06:31:57,728] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-24 06:31:57,751] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): my_etl> on 2022-06-24 06:31:57.067686+00:00
[2022-06-24 06:31:57,759] {standard_task_runner.py:52} INFO - Started process 701 to run task
[2022-06-24 06:31:57,764] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'my_etl', 'manual__2022-06-24T06:31:57.067686+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmp9j2uxygp', '--error-file', '/tmp/tmpqn13ui1z']
[2022-06-24 06:31:57,766] {standard_task_runner.py:80} INFO - Job 312: Subtask my_etl
[2022-06-24 06:31:57,853] {task_command.py:370} INFO - Running <TaskInstance: test.my_etl manual__2022-06-24T06:31:57.067686+00:00 [running]> on host 3c0196e07a8e
[2022-06-24 06:31:57,984] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=my_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-06-24T06:31:57.067686+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-24T06:31:57.067686+00:00
[2022-06-24 06:32:10,591] {python.py:173} INFO - Done. Returned value was: None
[2022-06-24 06:32:10,615] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=my_etl, execution_date=20220624T063157, start_date=20220624T063157, end_date=20220624T063210
[2022-06-24 06:32:10,666] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-24 06:32:10,706] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
