[2022-07-08 22:12:51,493] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.api_request manual__2022-07-08T22:07:49.368254+00:00 [queued]>
[2022-07-08 22:12:51,504] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.api_request manual__2022-07-08T22:07:49.368254+00:00 [queued]>
[2022-07-08 22:12:51,504] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 22:12:51,504] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-07-08 22:12:51,504] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 22:12:51,534] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): api_request> on 2022-07-08 22:07:49.368254+00:00
[2022-07-08 22:12:51,541] {standard_task_runner.py:52} INFO - Started process 2578 to run task
[2022-07-08 22:12:51,545] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'api_request', 'manual__2022-07-08T22:07:49.368254+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmp97_qmpm7', '--error-file', '/tmp/tmp6xid5alr']
[2022-07-08 22:12:51,546] {standard_task_runner.py:80} INFO - Job 409: Subtask api_request
[2022-07-08 22:12:51,610] {task_command.py:370} INFO - Running <TaskInstance: test.api_request manual__2022-07-08T22:07:49.368254+00:00 [running]> on host 3c0196e07a8e
[2022-07-08 22:12:51,735] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=api_request
AIRFLOW_CTX_EXECUTION_DATE=2022-07-08T22:07:49.368254+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-08T22:07:49.368254+00:00
[2022-07-08 22:12:52,419] {logging_mixin.py:115} INFO - Completed session
[2022-07-08 22:12:52,419] {python.py:173} INFO - Done. Returned value was:    CCSDS_OMM_VERS  ...                                          TLE_LINE2
0               2  ...  2 00005  34.2474  74.9161 1847158 131.7425 245...
1               2  ...  2 00011  32.8682 115.0114 1466442 172.2930 190...

[2 rows x 40 columns]
[2022-07-08 22:12:52,471] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-07-08 22:12:52,472] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2392, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-07-08 22:12:52,488] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test, task_id=api_request, execution_date=20220708T220749, start_date=20220708T221251, end_date=20220708T221252
[2022-07-08 22:12:52,526] {standard_task_runner.py:97} ERROR - Failed to execute job 409 for task api_request (Object of type DataFrame is not JSON serializable; 2578)
[2022-07-08 22:12:52,557] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-08 22:12:52,617] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
